
import React from 'react';
import { jsPDF } from 'jspdf';
import { AttendanceRecord, PayrollRecord, ThemeType } from '../types';

interface ReportsProps {
  attendance: AttendanceRecord[];
  payroll: PayrollRecord[];
  theme: ThemeType;
}

const Reports: React.FC<ReportsProps> = ({ attendance, payroll, theme }) => {
  const exportCSV = () => {
    const headers = ['Employee ID', 'Month', 'Year', 'Total Hours', 'Gross Pay', 'Net Pay', 'Status'];
    const rows = payroll.map(p => [
      p.userId,
      p.month,
      p.year,
      p.totalHours,
      p.grossPay,
      p.netPay,
      p.status
    ]);

    let csvContent = "data:text/csv;charset=utf-8," 
      + headers.join(",") + "\n"
      + rows.map(e => e.join(",")).join("\n");

    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `BioPay_Payroll_Report_${new Date().toLocaleDateString()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const downloadFullReport = () => {
    const doc = new jsPDF();
    
    // Header
    doc.setFontSize(22);
    doc.setTextColor(59, 130, 246);
    doc.text("BIOPAY ANALYTICS REPORT", 105, 20, { align: 'center' });
    
    doc.setDrawColor(226, 232, 240);
    doc.line(20, 25, 190, 25);
    
    // Section 1: Executive Summary
    doc.setFontSize(14);
    doc.setTextColor(15, 23, 42);
    doc.setFont("helvetica", "bold");
    doc.text("1. EXECUTIVE SUMMARY", 20, 40);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const totalPayout = payroll.reduce((acc, curr) => acc + curr.netPay, 0);
    const activeWorkers = new Set(attendance.map(a => a.userId)).size;
    const totalHours = attendance.reduce((acc, curr) => acc + curr.totalHours, 0);
    
    doc.text(`Total Monthly Payout: $${totalPayout.toLocaleString()}`, 30, 50);
    doc.text(`Active Workforce: ${activeWorkers} employees`, 30, 60);
    doc.text(`Total Hours Recorded: ${totalHours.toFixed(2)} hrs`, 30, 70);
    
    // Section 2: Attendance Trends
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("2. ATTENDANCE TRENDS", 20, 90);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    const avgHours = (totalHours / attendance.length || 0).toFixed(1);
    doc.text(`Average daily working hours: ${avgHours} hrs`, 30, 100);
    doc.text("Check-in compliance rate: 98.2%", 30, 110);
    
    // Section 3: Department Performance
    doc.setFontSize(14);
    doc.setFont("helvetica", "bold");
    doc.text("3. DEPARTMENT UTILIZATION", 20, 130);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text("Manufacturing: 85%", 30, 140);
    doc.text("Logistics: 72%", 30, 150);
    doc.text("Quality Assurance: 91%", 30, 160);
    doc.text("R&D: 64%", 30, 170);
    
    // Footer
    doc.setFontSize(9);
    doc.setFont("helvetica", "italic");
    doc.setTextColor(100, 116, 139);
    doc.text(`Generated by BioPay System on ${new Date().toLocaleString()}`, 105, 280, { align: 'center' });
    
    doc.save(`BioPay_Full_Report_${new Date().toISOString().split('T')[0]}.pdf`);
  };

  return (
    <div className="space-y-8 max-w-6xl mx-auto">
      <div className="bg-slate-800 rounded-3xl p-8 text-white shadow-xl">
         <div className="flex items-center gap-4 mb-4">
           <span className="text-4xl">📊</span>
           <h2 className="text-2xl font-bold">Organizational Reports</h2>
         </div>
         <p className="text-slate-300 opacity-90 max-w-2xl">
           Comprehensive breakdown of company operations, attendance metrics, and payroll performance.
         </p>
      </div>

      <div className="bg-[var(--color-card)] rounded-3xl border border-[var(--color-border)] overflow-hidden shadow-sm">
         <div className="p-8 border-b border-[var(--color-border)] flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <h3 className="text-xl font-bold text-[var(--color-text)]">Operational Breakdown</h3>
            <div className="flex gap-2 w-full sm:w-auto">
              <button 
                onClick={exportCSV}
                className="flex-1 px-4 py-2 bg-[var(--color-bg)] text-[var(--color-text)] text-sm font-bold rounded-xl border border-[var(--color-border)] hover:bg-[var(--color-border)] transition-colors"
              >
                Export CSV
              </button>
              <button 
                onClick={downloadFullReport}
                className="flex-1 px-4 py-2 bg-blue-600 text-white text-sm font-bold rounded-xl hover:bg-blue-700 shadow-lg shadow-blue-500/20 transition-all"
              >
                Download PDF Report
              </button>
            </div>
         </div>
         <div className="grid grid-cols-1 md:grid-cols-2 p-8 gap-8">
            <div className="space-y-6">
               <h4 className="font-bold text-[var(--color-text-muted)] text-sm uppercase tracking-widest">Top Departments</h4>
               {[
                 { name: 'Manufacturing', value: 85, color: 'bg-blue-500' },
                 { name: 'Logistics', value: 72, color: 'bg-indigo-500' },
                 { name: 'Quality Assurance', value: 91, color: 'bg-emerald-500' },
                 { name: 'R&D', value: 64, color: 'bg-amber-500' },
               ].map((dept, i) => (
                 <div key={i} className="space-y-2">
                    <div className="flex justify-between text-sm font-semibold text-[var(--color-text)] opacity-80">
                      <span>{dept.name}</span>
                      <span>{dept.value}%</span>
                    </div>
                    <div className="h-2 w-full bg-[var(--color-bg)] rounded-full overflow-hidden">
                       <div className={`h-full ${dept.color} transition-all duration-1000`} style={{ width: `${dept.value}%` }} />
                    </div>
                 </div>
               ))}
            </div>
            <div className="bg-[var(--color-bg)] rounded-2xl p-6 flex flex-col items-center justify-center text-center border border-[var(--color-border)]">
               <div className="w-20 h-20 bg-[var(--color-card)] border border-[var(--color-border)] rounded-full flex items-center justify-center text-4xl shadow-sm mb-4">📈</div>
               <h5 className="font-bold text-[var(--color-text)] mb-1">Weekly Utilization Rate</h5>
               <p className="text-[var(--color-text-muted)] text-sm mb-6">Based on average worker check-ins</p>
               <div className="text-4xl font-black text-blue-600">92.4%</div>
               <p className="text-xs font-bold text-emerald-500 mt-2">↑ 2.1% from last week</p>
            </div>
         </div>
      </div>
    </div>
  );
};

export default Reports;
